# This is a basic workflow to help you get started with Actions

name: extract-translators

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Every day at 3:30 AM UTC
    - cron:  '30 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.test }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          # make file runnable, might not be necessary
          chmod +x scripts/extract_translator.sh

          # run script
          ./scripts/extract_translator.sh --full -o scripts/translators.txt
          cat scripts/translators.txt
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add scripts/translators.txt
          git commit -m "Add changes"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          branch: master #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

